services:
  vaultwarden:
    image: vaultwarden/server:testing
    container_name: vaultwarden
    restart: unless-stopped
    ports:
     - 8445:80
    volumes:
     - ${MAINPATH}:/data
    environment:
     - WEBSOCKET_ENABLED=true
     - DOMAIN=${DOMAIN}
     #SMTP CONFIG
     - SMTP_HOST=smtp.gmail.com
     - SMTP_PORT=587
     - SMTP_SECURITY=starttls
     - SMTP_FROM=${SMTP_USERNAME}
     - SMTP_USERNAME=${SMTP_USERNAME}
     - SMTP_PASSWORD=${SMTP_PASSWORD}
     #ADMINISTRATION
     - SIGNUPS_ALLOWED=true 
     - ADMIN_TOKEN=${TOKEN} # REMOVING WILL DISABLE THE ADMIN PAGE