services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=${PUBLIC_IP}
      - WG_CONFIG_PORT=${WG_PORT}
      - LANG=en
      - PASSWORD_HASH=${HASH}
      - WG_DEFAULT_DNS=${DNS}
      - UI_TRAFFIC_STATS=true
      - UI_ENABLE_SORT_CLIENTS=true
      - MAX_AGE=30
      - UI_CHART_TYPE=1
    volumes:
      - ${MAINPATH}/etc-wg-easy:/etc/wireguard
    ports:
      - "${WG_PORT}:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "1080:80/tcp"
    environment:
      TZ: 'Europe/Lisbon'
      WEBPASSWORD: ${PASSWORD}
    volumes:
      - ${MAINPATH}/etc-pihole:/etc/pihole
      - ${MAINPATH}/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3

networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24