services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    user: "$UID:$GID"
    ports:
     - '3001:3000'
    volumes:
     - '${MAINPATH}:/var/lib/grafana'
