services:
  watchtower:
    restart: unless-stopped
    image: containrrr/watchtower
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
     - WATCHTOWER_CLEANUP=true
     - WATCHTOWER_SCHEDULE="0 0 4 * * *"
     #- WATCHTOWER_POLL_INTERVAL=3600
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"